# Site settings
title: CSS Dev
description: "ui 개발에 필요한 내용을 정리하고 있습니다."
url: "https://uidev-css.github.io/"

# Google Analytics
google_analytics: G-4E7S0P2MWC

# Author
author:
    name: CSS Dev
    url:
    email:

# Build settings
markdown: kramdown
include:
    - _pages

# Assets
sass:
    sass_dir: _sass
    style: compressed

# Gems
plugins:
    - jekyll-feed
    - jekyll-paginate
    - jekyll-seo-tag
    - jekyll-sitemap
    # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink: /:year-:month-:day/:title
paginate: 1000

# Excludes
exclude: [Gemfile, Gemfile.lock, tale.gemspec]

# Disqus (Set to your disqus id)
disqus: jekyll-tale
theme: jekyll-theme-cayman
